# Generated by Django 3.1.7 on 2021-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210411_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
